/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'badge-ink': '#9A6A00',
        secondary: '#7f5700',
        error: '#ba1a1a',
        'ink-secondary': '#555555',
        'on-background': '#1b1c1c',
        'surface-container-highest': '#e4e2e1',
        'secondary-fixed': '#ffdead',
        'coastal-blue': '#1C4DA6',
        'button-ink': '#241800',
        'tertiary-fixed-dim': '#b1d277',
        'border-line': '#E7E7E7',
        'wine-hover': '#A3263B',
        'tertiary-container': '#314800',
        'on-surface-variant': '#564243',
        'surface-bright': '#fcf9f8',
        'on-error': '#ffffff',
        'surface-parchment': '#FBF6EC',
        'on-secondary-fixed': '#281900',
        'inverse-on-surface': '#f3f0ef',
        'surface-variant': '#e4e2e1',
        'on-primary-container': '#ff8b96',
        'error-container': '#ffdad6',
        'secondary-container': '#feb62c',
        'inverse-primary': '#ffb2b7',
        'on-tertiary-fixed-variant': '#354e00',
        'inverse-surface': '#303030',
        background: '#fcf9f8',
        'on-tertiary-fixed': '#131f00',
        'gold-hover': '#D8950C',
        'surface-soft': '#F4F4F4',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#ffdadb',
        surface: '#fcf9f8',
        'surface-container-high': '#eae7e7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'on-secondary': '#ffffff',
        'primary-container': '#7a1f2e',
        'secondary-fixed-dim': '#ffba3c',
        'surface-tint': '#a03c49',
        'on-primary-fixed': '#40000e',
        'on-error-container': '#93000a',
        'surface-dim': '#dcd9d9',
        'surface-container': '#f0eded',
        'status-red': '#D62F3A',
        'outline-variant': '#dcc0c1',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#99b860',
        outline: '#897172',
        'primary-fixed-dim': '#ffb2b7',
        'pistachio-light': '#86A33E',
        'wine-dark': '#6E1626',
        'ink-tertiary': '#8A8A8A',
        primary: '#5b051a',
        'on-secondary-fixed-variant': '#604100',
        'on-primary-fixed-variant': '#812533',
        'on-secondary-container': '#6d4a00',
        tertiary: '#1f3000',
        'on-surface': '#1b1c1c',
        'tertiary-fixed': '#cdee90',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        'display-hero': ['"Libre Caslon Text"', 'serif'],
        'headline-lg': ['"Libre Caslon Text"', 'serif'],
        'headline-md': ['"Libre Caslon Text"', 'serif'],
        'headline-sm': ['"Libre Caslon Text"', 'serif'],
        'body-md': ['"Nunito Sans"', 'sans-serif'],
        'body-sm': ['"Nunito Sans"', 'sans-serif'],
        'body-lg': ['"Nunito Sans"', 'sans-serif'],
        subheading: ['"Nunito Sans"', 'sans-serif'],
        button: ['"Nunito Sans"', 'sans-serif'],
        'button-sm': ['"Nunito Sans"', 'sans-serif'],
        'label-caps': ['"Nunito Sans"', 'sans-serif'],
        caption: ['"Nunito Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['64px', { lineHeight: '72px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['46px', { lineHeight: '54px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        subheading: ['18px', { lineHeight: '26px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        button: ['15px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '700' }],
        'button-sm': ['13px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
